version: 2.1
jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: aws cloudformation deploy --stack-name udacity --template-body template.yml
workflows:
  my_workflow:
    jobs:
      - create_infrastructure